# Generated by Django 5.2 on 2025-04-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Profie",
            new_name="Profile",
        ),
    ]
